### ISSUE TITLE
Zabezpieczenie opcji administracyjnych przed nieautoryzowanym dostępem

### ISSUE THREAD

**Issue by apacewicz** [SIPSoftware/rcp-electron-angular#1]
Zwykły RCPUSER (bez uprawnień do modyfikacji) powinien widzieć:

- Ekran główny
- Logowanie

Analogicznie w chwili kiedy nie ma zalogowanego użytkownika (aktualnie można przeglądać konfigurację czy listę użytkowników).

![obraz](https://github.com/SIPSoftware/rcp-electron-angular/assets/78743154/91945c4e-0dc2-4012-a176-8965839ad718)

**Comment by olokup** [comment]
Zrobione w wersji 1.0.1
